apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: netflix-app
        image: azdevreg.azurecr.io/kdev:6
        ports:
        - containerPort: 80
        env:
        - name: VITE_APP_TMDB_V3_API_KEY
          valueFrom:
            secretKeyRef:
              name: tmdb-api-key
              key: VITE_APP_TMDB_V3_API_KEY
        - name: tmdb-api-key
          value: "https://api.themoviedb.org/3"
      imagePullSecrets:
      - name: acr-secret
